services:
  - type: web
    name: guido-sentiment-analysis
    env: python
    envVars:
      - key: CFLAGS
        value: "-std=c99"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
